<a href="https://colab.research.google.com/github/Meghashyamt/Telecom-Project/blob/master/Telecom_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# KNN

In [0]:
!git clone https://github.com/Meghashyamt/Telecom-Project

Cloning into 'Telecom-Project'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 42 (delta 17), reused 9 (delta 2), pack-reused 0
Unpacking objects: 100% (42/42), done.

In [0]:
#import libraries
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sb

from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [0]:
data = pd.read_csv("Telecom-Project/telecom_churn_data.csv")
data.head(2)

  State  Account Length  ...  Custserve calls  Churn
0    KS             128  ...                 1     0
1    OH             107  ...                 1     0

[2 rows x 21 columns]

In [0]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4617 entries, 0 to 4616
Data columns (total 21 columns):
State                   4617 non-null object
Account Length          4617 non-null int64
Area code               4617 non-null int64
Phone                   4617 non-null object
International Plan      4617 non-null object
Vmail plan              4617 non-null object
Vmail Message           4617 non-null int64
Day mins                4617 non-null float64
Day calls               4617 non-null int64
Day charge              4617 non-null float64
Eve mins                4617 non-null float64
Eve calls               4617 non-null int64
Eve charge              4617 non-null float64
Night mins              4617 non-null float64
Night calls             4617 non-null int64
Night charge            4617 non-null float64
International mins      4617 non-null float64
International calls     4617 non-null int64
International charge    4617 non-null float64
Custserve calls         4617 non-null int64
Churn                   4617 non-null int64
dtypes: float64(8), int64(9), object(4)
memory usage: 757.6+ KB

In [0]:
data.drop("Phone", axis=1)

     State  Account Length  ...  Custserve calls  Churn
0       KS             128  ...                 1     0
1       OH             107  ...                 1     0
2       NJ             137  ...                 0     0
3       OH              84  ...                 2     0
4       OK              75  ...                 3     0
5       AL             118  ...                 0     0
6       MA             121  ...                 3     0
7       MO             147  ...                 0     0
8       LA             117  ...                 1     0
9       WV             141  ...                 0     0
10      IN              65  ...                 4     1
11      RI              74  ...                 0     0
12      IA             168  ...                 1     0
13      MT              95  ...                 3     0
14      IA              62  ...                 4     0
15      NY             161  ...                 4     1
16      ID              85  ...                 1     0
17      VT              93  ...                 3     0
18      VA              76  ...                 1     0
19      TX              73  ...                 1     0
20      FL             147  ...                 0     0
21      CO              77  ...                 5     1
22      AZ             130  ...                 0     0
23      SC             111  ...                 2     0
24      VA             132  ...                 0     0
25      NE             174  ...                 3     0
26      WY              57  ...                 0     0
27      MT              54  ...                 3     0
28      MO              20  ...                 0     0
29      HI              49  ...                 1     0
...    ...             ...  ...               ...   ...
4587    RI             106  ...                 2     0
4588    LA              81  ...                 2     0
4589    HI              33  ...                 3     0
4590    KY              77  ...                 1     0
4591    DE              87  ...                 1     0
4592    SD              72  ...                 4     1
4593    MS              45  ...                 0     0
4594    WI              41  ...                 0     0
4595    VT             122  ...                 1     0
4596    MA              92  ...                 0     0
4597    OR              65  ...                 1     1
4598    MA              57  ...                 1     0
4599    MT             127  ...                 0     1
4600    AK             121  ...                 2     0
4601    MS             117  ...                 1     0
4602    OR              37  ...                 3     0
4603    VA             162  ...                 1     0
4604    AZ             193  ...                 3     0
4605    UT              80  ...                 2     0
4606    WV             176  ...                 1     0
4607    MN              76  ...                 1     0
4608    AZ              89  ...                 1     0
4609    RI             128  ...                 1     0
4610    NM             138  ...                 0     0
4611    HI              90  ...                 3     0
4612    NY              57  ...                 3     0
4613    NM             177  ...                 3     0
4614    VT              67  ...                 1     0
4615    MI              98  ...                 0     0
4616    IN             140  ...                 2     0

[4617 rows x 20 columns]

In [0]:
data['ChurnFlag']=(data['Churn']==True).astype(int)

In [0]:
#X and y slice
X=data.iloc[:,1:19]
y=data.iloc[:,21]

In [0]:
X=pd.get_dummies(X, drop_first=True)

In [0]:
#KNN Model
model =KNeighborsClassifier(n_neighbors=7)

In [0]:
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.20, random_state=10)

In [0]:
model.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [0]:
predict=model.predict(X_test)

In [0]:
accuracy_score(y_test, predict)

0.8874458874458875

In [0]:
confusion_matrix(y_test, predict)

array([[785,  14],
       [ 90,  35]])

In [0]:
print(classification_report(y_test, predict))

              precision    recall  f1-score   support

           0       0.90      0.98      0.94       799
           1       0.71      0.28      0.40       125

    accuracy                           0.89       924
   macro avg       0.81      0.63      0.67       924
weighted avg       0.87      0.89      0.87       924